export type Leitura = {
  id?: number | string;
  idLeitura?: number | string;
  temperatura?: number | string;
  umidade?: number | string;
  indiceUv?: number | string;
  uvIndex?: number | string;
  chuva?: number | string;
  rainfall?: number | string;
  gasFumaca?: number | string;
  gasSmoke?: number | string;
  distanciaAguaCm?: number | string;
  nivelAguaPercentual?: number | string;
  inclinacaoGraus?: number | string;
  vibracao?: number | string;
  pressaoHpa?: number | string;
  pm25?: number | string;
  pm10?: number | string;
  dataHora?: string;
  timestamp?: string;
  createdAt?: string;
  dtLeitura?: string;
  dtRecebidoEm?: string;
  [key: string]: unknown;
};

export type LeituraReadModel = {
  id: number | string;
  temperatura?: number;
  umidade?: number;
  indiceUv?: number;
  chuva?: number;
  gasFumaca?: number;
  distanciaAguaCm?: number;
  nivelAguaPercentual?: number;
  inclinacaoGraus?: number;
  vibracao?: number;
  pressaoHpa?: number;
  pm25?: number;
  pm10?: number;
  dataHora?: string;
  raw?: Leitura;
};
